### ISSUE TITLE
Move manual into its own repo

### ISSUE THREAD

**Issue by kerrizor** [shoes/shoesrb.com#46]
@PragTob made the comment in a PR.

What would be the best approach?

**Comment by PragTob** [comment]
So the thing is the following:

Right now there basically is HTML generated from the manual markdown file in this repository. The real source file for the manual is in the shoes repository and in the shoes4 repository ([manual-en.txt](https://github.com/shoes/shoes4/blob/master/static/manual-en.txt)). The markdown files are used for our built in manual there.

I would want to have this all in one place and then the others just use that one file so that they do not get out of sync. E.g. I don't want someone to change something in the HTML here that is not propagated back to the original markdown.

We could just manually copy it over every once in a while (from a manual repository) but maybe a gem would be better, because you know GEMIFY ALL THE THINGS - so we could serve that as a gem for shoes4/3 (or maybe we just leave 3 alone) and have it as a dependency. The website should be able to just use the markdown. Right now the manual is just one gigantic file so it might be good to split that up to multiple files (according to sub pages), as I dunno if jekyll can handle that one big markdown file the way we want it to handle (with subpages). So either multiple files (should work) or we build a rake task that compiles the HTML files.

So yeah what do you think about that @steveklabnik @jrgifford @wasnotrice @wpp @ashbb ?

Cheers,
Tobi

**Comment by jrgifford** [comment]
If we are gemifying all the things, then make the website use the gem too.
:P

I like it. :)

**Comment by PragTob** [comment]
@jrgifford would love for the website to use the gem, but github pages can't do that afaik so we'd need the rake task to generate the stuff :'-(

**Comment by jrgifford** [comment]
@pragtob ew. Nevermind.

## 

James Gifford
cell: 2162238574
Snowy Penguin Solutions, LLC | http://snowypenguinsolutions.com

**Comment by PragTob** [comment]
Moved to shoes/shoes4#745 for better visibility
